eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: api-gateway-web
zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    tuk-management-service:
      path: /management/**
      serviceId: tuk-management-service
    acessor-management-service:
      path: /user/**
      serviceId: acessor-management-service




